springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: -1
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false